use crate::mesh::Mesh;
use crate::params::Params;
use crate::integrate::group_moduli;
use anyhow::Result;
use std::fs::File; 
use std::io::{Write, BufWriter};

pub fn write_abq(mesh: &Mesh, per_part_moduli: &Vec<Vec<f64>>, params: &Params, orig_mesh_path: &str) -> Result<String> {
	let out_path = if let Some(stripped) = orig_mesh_path.strip_suffix(".inp") { format!("{}MAT.inp", stripped)} else { format!("{orig_mesh_path}_MAT.inp") };
	let mut f = BufWriter::new(File::create(&out_path)?);
	
	// Extract base name for job/model name
	let base_name = if orig_mesh_path.ends_with(".inp") {
		std::path::Path::new(orig_mesh_path).file_stem().unwrap().to_str().unwrap()
	} else {
		std::path::Path::new(orig_mesh_path).file_name().unwrap().to_str().unwrap()
	};
	
	// Write proper Abaqus header
	writeln!(f, "*Heading")?;
	writeln!(f, "** Job name: {} Model name: {}", base_name, base_name)?;
	writeln!(f, "**  Generated by luma - {}",
		env!("CARGO_PKG_VERSION")
	)?;
	writeln!(f, "*Preprint, echo=NO, model=NO, history=NO, contact=NO")?;
	writeln!(f, "**")?;
	if let Some(name) = &mesh.parts[0].name {
		writeln!(f, "** PARTS")?;
		writeln!(f, "**")?;
	}
	
	// First pass: collect all raw moduli globally
	let mut all_raw_moduli = Vec::new();
	
	for (pi, part) in mesh.parts.iter().enumerate() {
		if !part.ignore {
			// Collect raw moduli from all parts BEFORE binning
			all_raw_moduli.extend(&per_part_moduli[pi]);
		}
	}
	
	// Apply binning globally to all moduli
	let all_grouped_moduli = group_moduli(&all_raw_moduli, params);
	
	// Create global unique material list from globally binned moduli
	let mut all_grouped_materials = all_grouped_moduli.clone();
	all_grouped_materials.sort_by(|a,b| a.partial_cmp(b).unwrap());
	all_grouped_materials.dedup();
	
	// Create per-part grouped data for element assignment
	let mut part_grouped_data = Vec::new();
	let mut global_idx = 0;
	for (pi, part) in mesh.parts.iter().enumerate() {
		if !part.ignore && pi < per_part_moduli.len() {
			let part_size = per_part_moduli[pi].len();
			let part_grouped: Vec<f64> = all_grouped_moduli[global_idx..global_idx + part_size].to_vec();
			global_idx += part_size;
			let mut part_unique = part_grouped.clone();
			part_unique.sort_by(|a, b| a.partial_cmp(b).unwrap());
			part_unique.dedup();
			part_grouped_data.push((part_grouped, part_unique));
		} else {
			part_grouped_data.push((vec![], vec![]));
		}
	}
	
	// Create a map from material value to material index
	let mut material_map = std::collections::HashMap::new();
	for (i, &mat_val) in all_grouped_materials.iter().enumerate() {
		material_map.insert((mat_val * 1e9).round() as i64, i + 1); // Use rounded value as key to handle floating point precision
	}
	
	for (pi, part) in mesh.parts.iter().enumerate() {
		if let Some(name) = &part.name {
			writeln!(f, "*Part, name={}", name)?;
		}
		// nodes
		writeln!(f, "*Node")?;
		for n in &part.nodes {
			writeln!(f, "{}, {:.9}, {:.9}, {:.9}", n.id, n.x, n.y, n.z)?;
		}
		if !part.elements.is_empty() {
			let etype = match part.elements[0].kind {
				crate::mesh::ElementKind::Tet4 => "C3D4",
				crate::mesh::ElementKind::Tet10 => "C3D10",
				crate::mesh::ElementKind::Hex8 => "C3D8",
				crate::mesh::ElementKind::Wedge6 => "C3D6"
			};
			writeln!(f, "*Element, type={}", etype)?;
			for e in &part.elements {
				let nodes: Vec<String> = e.nodes.iter().map(|n| n.to_string()).collect();
				writeln!(f, "{}, {}", e.id, nodes.join(", "))?;
			}
		}
		if !part.ignore {
			let (grouped, uniq) = &part_grouped_data[pi];
			for (i, mval) in uniq.iter().enumerate() {
				if let Some(name) = &part.name {
					writeln!(f, "*Elset, elset=BoneMatSet_{}_{}", name, i+1)?;
				} else {
					writeln!(f, "*Elset, elset=BoneMatSet_{}", i+1)?;
				}
				let mut element_ids = Vec::new();
				for (ei, m) in grouped.iter().enumerate() {
					if (m - mval).abs() < 1e-9 {
						element_ids.push(part.elements[ei].id);
					}
				}
				
				// Write element IDs with proper line wrapping (max 16 items per line)
				for (idx, chunk) in element_ids.chunks(16).enumerate() {
					if idx > 0 {
						writeln!(f)?; // End previous line
					}
					for (i, &element_id) in chunk.iter().enumerate() {
						if i > 0 {
							write!(f, ", ")?;
						}
						write!(f, "{}", element_id)?;
					}
				}
				writeln!(f)?; // End the last line
			}
			writeln!(f, "**")?;
			writeln!(f, "** SOLID SECTIONS")?;
			writeln!(f, "**")?;
			// Add solid sections that link element sets to materials
			for (i, mval) in uniq.iter().enumerate() {
				let material_index = material_map.get(&((*mval * 1e9).round() as i64)).unwrap_or(&1);
				if let Some(name) = &part.name {
					writeln!(f, "*Solid Section, elset=BoneMatSet_{}_{}, material=BoneMat_{}", name, i+1, material_index)?;
				} else {
					writeln!(f, "*Solid Section, elset=BoneMatSet_{}, material=BoneMat_{}", i+1, material_index)?;
				}
			}
		}
		if let Some(name) = &part.name {
			writeln!(f, "*End Part")?;
		}
	}

	if let Some(name) = &mesh.parts[0].name {
		writeln!(f, "**")?;
		writeln!(f, "** ASSEMBLY")?;
		writeln!(f, "**")?;
		// Assembly
		writeln!(f, "*Assembly, name=Assembly")?;
		for p in &mesh.parts {
			writeln!(f, "*Instance, name={}, part={}", p.name.as_deref().unwrap(), p.name.as_deref().unwrap())?;
		}
		writeln!(f, "*End Instance")?;
		writeln!(f, "**")?;
		writeln!(f, "*End Assembly")?;
	}
	writeln!(f, "**")?;
	writeln!(f, "** MATERIALS")?;
	writeln!(f, "**")?;
	// Materials section - use the global grouped materials
	for (i, m) in all_grouped_materials.iter().enumerate() { 
		writeln!(f, "*Material, name=BoneMat_{}", i+1)?; 
		writeln!(f, "*Elastic")?; 
		writeln!(f, "{}, {}", m, params.poisson)?; 
		writeln!(f, "*Density")?;
		let density_value: f64 = if params.back_calculation {
			params.density_back_calculation(*m)
		} else {
			*m
		};
		writeln!(f, "{}", density_value)?;
	}
	Ok(out_path)
}