use crate::mesh::{Mesh, Node, Element, ElementKind};
use crate::params::Params;
use crate::integrate::group_moduli;
use anyhow::Result;
use std::fs::File;
use std::io::{Write, BufWriter};
use std::collections::HashMap;

// Platform-specific line endings for ANSYS compatibility
#[cfg(windows)]
const NL: &str = "\r";
#[cfg(not(windows))]
const NL: &str = "\r"; // ANSYS files always need CRLF regardless of platform

/// Write CDB file
pub fn write_cdb(mesh: &Mesh, per_part_moduli: &[Vec<f64>], params: &Params, orig_mesh_path: &str) -> Result<String> {
    let out_path = if let Some(stripped) = orig_mesh_path.strip_suffix(".cdb") { format!("{}MAT.cdb", stripped)} else { format!("{orig_mesh_path}_MAT.cdb") };
    
    let file = File::create(&out_path)?;
    let mut writer = BufWriter::new(file);
    
    let mut exporter = CdbExporter::new(&mut writer);
    exporter.write_mesh(mesh, per_part_moduli, params)?;
    
    Ok(out_path)
}

struct CdbExporter<W: Write> {
    writer: W,
}

impl<W: Write> CdbExporter<W> {
    fn new(writer: W) -> Self {
        Self { writer }
    }
    
    fn write_mesh(&mut self, mesh: &Mesh, per_part_moduli: &[Vec<f64>], params: &Params) -> Result<()> {
        // Write header
        self.write_header()?;
        
        // Collect all data from non-ignored parts
        let mut all_nodes = Vec::new();
        let mut all_elements = Vec::new();
        let mut material_assignments = Vec::new();
        let mut unique_materials = Vec::new();
        
        // Collect all raw moduli globally
        let mut all_raw_moduli = Vec::new();
        
        for (pi, part) in mesh.parts.iter().enumerate() {
            if !part.ignore && pi < per_part_moduli.len() {
                // Collect nodes
                all_nodes.extend(part.nodes.iter().cloned());
                
                // Collect elements
                all_elements.extend(part.elements.iter().cloned());
                
                // Collect raw moduli from all parts before binning
                all_raw_moduli.extend(&per_part_moduli[pi]);
            }
        }
        
        // Apply binning globally to ALL moduli
        let element_moduli = group_moduli(&all_raw_moduli, params);
        
        // Collect unique materials from globally binned moduli
        for &modulus in &element_moduli {
            if !unique_materials.iter().any(|&m: &f64| (m - modulus).abs() < 1e-10_f64) {
                unique_materials.push(modulus);
            }
        }
        
        // Sort materials for consistent output
        unique_materials.sort_by(|a, b| a.partial_cmp(b).unwrap());
        
        // Create material assignments using sorted material list
        for (elem_idx, &modulus) in element_moduli.iter().enumerate() {
            if let Some(mat_pos) = unique_materials.iter().position(|&m: &f64| (m - modulus).abs() < 1e-10_f64) {
                let material_id = mat_pos + 1; // 1-based indexing
                material_assignments.push((elem_idx, material_id));
            }
        }
        
        // Write sections
        self.write_nblock(&all_nodes)?;
        self.write_element_type_definitions()?;
        self.write_eblock(&all_elements, &material_assignments)?;
        self.write_materials(&unique_materials, params)?;
        
        Ok(())
    }
    
    fn write_header(&mut self) -> Result<()> {
        // Write header
        writeln!(self.writer, "!! Generated by luma - {}{}", env!("CARGO_PKG_VERSION"), NL)?;
        write!(self.writer, "{}", NL)?;
        writeln!(self.writer, "/PREP7{}", NL)?;
        Ok(())
    }
    
    /// Write NBLOCK section
    fn write_nblock(&mut self, nodes: &[Node]) -> Result<()> {
        if nodes.is_empty() {
            return Ok(());
        }
        
        // Find max node ID for format calculation
        let max_node_id = nodes.iter().map(|n| n.id).max().unwrap_or(0);
        
        // Calculate integer field width
        let int_char_size = format!("{}", max_node_id).len();
        
        // Write NBLOCK header
        writeln!(self.writer, "NBLOCK,6,SOLID,{:>10},{:>10}{}", 
                 max_node_id, nodes.len(), NL)?;
        
        // Write format specification
        writeln!(self.writer, "(3i{},6e22.13){}", int_char_size + 1, NL)?;
        
        // Write node data with fixed-width format
        for node in nodes {
            // Format: nodeId, solid_model_entity_id, line_num, x, y, z
            // proper E+003 formatting
            let x_formatted = format_scientific_13_digits(node.x);
            let y_formatted = format_scientific_13_digits(node.y);
            let z_formatted = format_scientific_13_digits(node.z);
            writeln!(self.writer, "{:>width$} {:>width$} {:>width$} {:>21} {:>21} {:>21}{}", 
                     node.id, 0, 0, x_formatted, y_formatted, z_formatted, NL,
                     width = int_char_size)?;
        }
        
        // Terminator
        writeln!(self.writer, "N,R5.3,LOC,-1,{}", NL)?;
        
        Ok(())
    }
    
    /// Write element type definitions before EBLOCK
    fn write_element_type_definitions(&mut self) -> Result<()> {
        // Define element type 1 as 187 (TET10/TET4)
        writeln!(self.writer, "ET,1,187{}", NL)?;
        Ok(())
    }
    
    /// Write EBLOCK section
    fn write_eblock(&mut self, elements: &[Element], material_assignments: &[(usize, usize)]) -> Result<()> {
        if elements.is_empty() {
            return Ok(());
        }
        
        // Create material assignment map
        let mut element_materials: HashMap<usize, usize> = HashMap::new();
        for &(elem_idx, mat_id) in material_assignments {
            element_materials.insert(elem_idx, mat_id);
        }
        
        // Find max element ID
        let max_elem_id = elements.iter().map(|e| e.id).max().unwrap_or(0);
        
        // Calculate integer field width
        let int_char_size = format!("{}", max_elem_id).len();
        
        // Write EBLOCK header
        writeln!(self.writer, "EBLOCK,19,SOLID,{:>10},{:>10}{}", 
                 max_elem_id, elements.len(), NL)?;
        
        // Write format specification
        writeln!(self.writer, "(19i{}){}", int_char_size + 1, NL)?;
        
        // Write element data
        for (elem_idx, element) in elements.iter().enumerate() {
            let material_id = element_materials.get(&elem_idx).unwrap_or(&1);
            let element_type = self.get_ansys_element_type(&element.kind);
            let node_count = element.nodes.len();
            
            // Write main element line (19 fields following ANSYS EBLOCK specification)
            // Format: mat_id, elem_type, real_const, sect_num, coord_sys, birth_death, solid_model_ref, elem_shape, node_count, unused, elem_id, [node_ids...]
            write!(self.writer, "{:>width$} {:>width$} {:>width$} {:>width$} {:>width$} {:>width$} {:>width$} {:>width$} {:>width$} {:>width$} {:>width$}",
                   material_id, element_type, 1, 1, 0, 0, 0, 0, node_count, 0, element.id,
                   width = int_char_size)?;
            
            // Write node IDs
            for (i, &node_id) in element.nodes.iter().enumerate() {
                if i > 0 && i % 8 == 0 {
                    // Start new line for additional nodes
                    writeln!(self.writer, "{}", NL)?;
                }
                write!(self.writer, " {:>width$}", node_id, width = int_char_size)?;
            }
            
            writeln!(self.writer, "{}", NL)?;
        }
        
        // Terminator
        writeln!(self.writer, "{:>width$}{}", -1, NL, width = int_char_size)?;
        
        Ok(())
    }
    
    /// Format number as decimal with 8 decimal places for ANSYS materials
    fn format_decimal_8_places(value: f64) -> String {
        format!("{:.8}", value)
    }
    
    /// Write material data following ANSYS MPDATA/MPTEMP format
    fn write_materials(&mut self, materials: &[f64], params: &Params) -> Result<()> {
        if materials.is_empty() {
            return Ok(());
        }
        
        writeln!(self.writer, "!! Material Properties{}", NL)?;
        
        for (i, &modulus) in materials.iter().enumerate() {
            let material_id = i + 1; // 1-based indexing
            
            // Write EX (Young's modulus) with MPTEMP first
            writeln!(self.writer, "MPTEMP,R5.0, 1, 1, {:<16},{}", 
                     Self::format_decimal_8_places(0.0), NL)?;  // Temperature 0.0
            writeln!(self.writer, "MPDATA,R5.0, 1,EX,{:>6}, 1, {:<16},{}", 
                     material_id, Self::format_decimal_8_places(modulus), NL)?;
            
            // Write NUXY (Poisson's ratio) with MPTEMP first  
            writeln!(self.writer, "MPTEMP,R5.0, 1, 1, {:<16},{}", 
                     Self::format_decimal_8_places(0.0), NL)?;  // Temperature 0.0
            writeln!(self.writer, "MPDATA,R5.0, 1,NUXY,{:>6}, 1, {:<16},{}", 
                     material_id, Self::format_decimal_8_places(params.poisson), NL)?;
            
            // Write DENS (density) with MPTEMP first
            writeln!(self.writer, "MPTEMP,R5.0, 1, 1, {:<16},{}", 
                   Self::format_decimal_8_places(0.0), NL)?;  // Temperature 0.0
            // Use density back calculation if enabled, otherwise use modulus as density
            let density_value = if params.back_calculation {
                params.density_back_calculation(modulus)
            } else {
                modulus  // Use modulus for density (original behavior)
            };
            writeln!(self.writer, "MPDATA,R5.0, 1,DENS,{:>6}, 1, {:<16},{}", 
                   material_id, Self::format_decimal_8_places(density_value), NL)?;  // Use calculated density
        }
        
        // End with FINISH command
        writeln!(self.writer, "FINISH{}", NL)?;
        
        Ok(())
    }
    
    /// Get or create material ID for given modulus
    fn get_or_create_material_id(&self, modulus: f64, unique_materials: &mut Vec<f64>) -> usize {
        // Find existing material or add new one
        if let Some(pos) = unique_materials.iter()
            .position(|&m| (m - modulus).abs() < f64::EPSILON) {
            pos + 1 // 1-based indexing
        } else {
            unique_materials.push(modulus);
            unique_materials.len() // 1-based indexing
        }
    }
    
    /// Map element kind to ANSYS element type ID (all use type 1 which is defined as ET,1,187)
    fn get_ansys_element_type(&self, kind: &ElementKind) -> u32 {
        match kind {
            ElementKind::Tet4 => 1,     // Use element type 1 (defined as SOLID187)
            ElementKind::Tet10 => 1,    // Use element type 1 (defined as SOLID187)  
            ElementKind::Hex8 => 1,     // Use element type 1 (defined as SOLID187)
            ElementKind::Wedge6 => 1,   // Use element type 1 (defined as SOLID187)
        }
    }
}

/// Ensure three-digit exponent format for ANSYS compatibility
fn format_scientific_with_three_digit_exponent(value: f64) -> String {
    let formatted = format!("{:.6E}", value);
    
    // Convert E1 to E+001, E+1 to E+001, E-1 to E-001, etc.
    if let Some(e_pos) = formatted.find('E') {
        let (mantissa, exponent) = formatted.split_at(e_pos + 1);
        let exp_value: i32 = exponent.parse().unwrap_or(0);
        format!("{}{:+04}", mantissa, exp_value)
    } else {
        formatted
    }
}

/// Format with 13 decimal places and proper E format 
fn format_scientific_13_digits(value: f64) -> String {
    let formatted = format!("{:.13E}", value);
    
    if let Some(e_pos) = formatted.find('E') {
        let (mantissa, exponent) = formatted.split_at(e_pos + 1);
        let exp_value: i32 = exponent.parse().unwrap_or(0);
        format!("{}{:+04}", mantissa, exp_value)
    } else {
        formatted
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mesh::{Node, Element, ElementKind, Part};
    
    #[test]
    fn test_cdb_export_basic() {
        let nodes = vec![
            Node { id: 1, x: 0.0, y: 0.0, z: 0.0 },
            Node { id: 2, x: 1.0, y: 0.0, z: 0.0 },
            Node { id: 3, x: 0.0, y: 1.0, z: 0.0 },
            Node { id: 4, x: 0.0, y: 0.0, z: 1.0 },
        ];
        
        let elements = vec![
            Element {
                id: 1,
                nodes: vec![1, 2, 3, 4],
                kind: ElementKind::Tet4,
            },
        ];
        
        let node_index = nodes.iter().enumerate()
            .map(|(i, n)| (n.id, i))
            .collect();
        
        let part = Part {
            name: Some("TestPart".to_string()),
            nodes,
            elements,
            node_index,
            ignore: false,
        };
        
        let mesh = Mesh {
            parts: vec![part],
            mesh_format_info: None,
        };
        
        let moduli = vec![vec![200000.0]]; // One material
        let params = Params {
            integration: None,
            gap_value: Some(1.0),
            num_materials: None,
            grouping_density: "mean".to_string(),
            int_steps: 10,
            rho_qct_a: 1.0,
            rho_qct_b: 1.0,
            calibration_correct: false,
            back_calculation: true,
            min_val: 0.0,
            poisson: 0.3,
            num_e_param: "single".to_string(),
            num_ct_param: None,
            rho_thresh1: None, rho_thresh2: None,
            ethresh1: None, ethresh2: None,
            rho_asha1: None, rho_ashb1: None,
            rho_asha2: None, rho_ashb2: None,
            rho_asha3: None, rho_ashb3: None,
            ea1: 1000.0, eb1: 1000.0, ec1: 1000.0,
            ea2: None, eb2: None, ec2: None,
            ea3: None, eb3: None, ec3: None,
            integration_scheme: "dense".to_string(),
            ignore: vec![],
            mesh_translate_x: None, mesh_translate_y: None, mesh_translate_z: None,
            mesh_rotate_x: None, mesh_rotate_y: None, mesh_rotate_z: None,
            histogram_export: false,

            histogram_dir: None,
        };
        
        let result = write_cdb(&mesh, &moduli, &params, "test.cdb");
        assert!(result.is_ok());
    }

    #[test]
    fn test_scientific_formatting() {
        assert_eq!(format_scientific_with_three_digit_exponent(1000.0), "1.000000E+003");
        assert_eq!(format_scientific_with_three_digit_exponent(0.001), "1.000000E-003");
        assert_eq!(format_scientific_with_three_digit_exponent(1.5e10), "1.500000E+010");
        
        assert_eq!(format_scientific_13_digits(1000.0), "1.0000000000000E+003");
        assert_eq!(format_scientific_13_digits(0.001), "1.0000000000000E-003");
        assert_eq!(format_scientific_13_digits(1.5e10), "1.5000000000000E+010");
    }
}
