use anyhow::{anyhow, Result};
use std::collections::{BTreeMap, HashMap};
use std::fs;
use std::fs::File;
use std::io::{BufWriter, Write};

use super::{Element, ElementKind, Mesh, MeshFormatInfo, Node, Part};
use crate::integrate::group_moduli;
use crate::params::Params;

#[derive(Debug, Clone)]
struct ParsedFebioMesh {
	name: String,
	nodes: Vec<Node>,
	element_blocks: Vec<ParsedElementBlock>,
	material_moduli_by_name: HashMap<String, f64>,
	domain_material_by_set: HashMap<String, String>,
	element_data_by_set: HashMap<String, Vec<f64>>,
}

#[derive(Debug, Clone)]
struct ParsedElementBlock {
	name: Option<String>,
	kind: ElementKind,
	elements: Vec<Element>,
}

pub fn parse_feb(path: &str, ignore: &[String]) -> Result<Mesh> {
	let parsed = parse_febio_file(path)?;
	let ignore_name = ignore.iter().any(|candidate| candidate.eq_ignore_ascii_case(&parsed.name));
	let elements = parsed
		.element_blocks
		.iter()
		.flat_map(|block| block.elements.clone())
		.collect::<Vec<_>>();

	let mut node_index = HashMap::with_capacity(parsed.nodes.len());
	for (index, node) in parsed.nodes.iter().enumerate() {
		node_index.insert(node.id, index);
	}

	Ok(Mesh {
		parts: vec![Part {
			name: Some(parsed.name),
			nodes: parsed.nodes,
			elements,
			node_index,
			ignore: ignore_name,
		}],
		mesh_format_info: Some(MeshFormatInfo::default()),
	})
}

pub fn parse_feb_with_materials(path: &str, ignore: &[String]) -> Result<(Mesh, Vec<Vec<f64>>)> {
	let parsed = parse_febio_file(path)?;
	let mesh = parse_feb(path, ignore)?;
	let mut per_part = vec![vec![0.0; mesh.parts[0].elements.len()]];
	let mut element_index = 0usize;

	for block in &parsed.element_blocks {
		let modulus_from_domain = block
			.name
			.as_ref()
			.and_then(|set_name| parsed.domain_material_by_set.get(set_name))
			.and_then(|material_name| lookup_material_modulus(&parsed.material_moduli_by_name, material_name));
		let element_data = block
			.name
			.as_ref()
			.and_then(|set_name| parsed.element_data_by_set.get(set_name));

		for (offset, _element) in block.elements.iter().enumerate() {
			let value = modulus_from_domain
				.or_else(|| element_data.and_then(|values| values.get(offset).copied()))
				.unwrap_or(0.0);
			if let Some(slot) = per_part[0].get_mut(element_index) {
				*slot = value;
			}
			element_index += 1;
		}
	}

	Ok((mesh, per_part))
}

pub fn write_feb(mesh: &Mesh, per_part_moduli: &[Vec<f64>], params: &Params, orig_mesh_path: &str) -> Result<String> {
	let out_path = output_path(orig_mesh_path);
	let file = File::create(&out_path)?;
	let mut writer = BufWriter::new(file);
	let model_name = model_name_from_path(orig_mesh_path);

	let parts = mesh.parts.iter().filter(|part| !part.ignore).collect::<Vec<_>>();
	if parts.is_empty() {
		return Err(anyhow!("FEBio export requires at least one non-ignored part"));
	}

	let grouped_moduli = collect_grouped_moduli(&parts, per_part_moduli, params)?;
	let materials = collect_materials(&grouped_moduli)?;
	let groups = collect_groups(&parts, &grouped_moduli, &materials)?;
	let all_nodes = collect_nodes(&parts);

	writeln!(writer, "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>")?;
	writeln!(writer, "<!-- Generated by LUMA - {} -->", env!("CARGO_PKG_VERSION"))?; 
	writeln!(writer, "<febio_spec version=\"4.0\">")?;
	writeln!(writer, "\t<Module type=\"solid\"/>")?;
	writeln!(writer, "\t<Globals>")?;
	writeln!(writer, "\t\t<Constants>")?;
	writeln!(writer, "\t\t\t<T>0</T>")?;
	writeln!(writer, "\t\t\t<P>0</P>")?;
	writeln!(writer, "\t\t\t<R>0</R>")?;
	writeln!(writer, "\t\t\t<Fc>0</Fc>")?;
	writeln!(writer, "\t\t</Constants>")?;
	writeln!(writer, "\t</Globals>")?;
	writeln!(writer, "\t<Material>")?;
	for (index, modulus) in materials.iter().enumerate() {
		let material_name = format!("Mat_{}", index + 1);
		writeln!(writer, "\t\t<material id=\"{}\" name=\"{}\" type=\"isotropic elastic\">", index + 1, material_name)?;
		let density = if params.back_calculation { params.density_back_calculation(*modulus) } else { 1.0 };
		writeln!(writer, "\t\t\t<density>{}</density>", format_modulus(density))?;
		writeln!(writer, "\t\t\t<E>{}</E>", format_modulus(*modulus))?;
		writeln!(writer, "\t\t\t<v>{}</v>", params.poisson)?;
		writeln!(writer, "\t\t</material>")?;
	}
	writeln!(writer, "\t</Material>")?;
	writeln!(writer, "\t<Mesh>")?;
	writeln!(writer, "\t\t<Nodes name=\"{}\">", xml_escape(&model_name))?;
	for node in &all_nodes {
		writeln!(writer, "\t\t\t<node id=\"{}\">{:.10e},{:.10e},{:.10e}</node>", node.id, node.x, node.y, node.z)?;
	}
	writeln!(writer, "\t\t</Nodes>")?;
	for group in &groups {
		writeln!(writer, "\t\t<Elements type=\"{}\" name=\"{}\">", group.element_type, xml_escape(&group.set_name))?;
		for element in &group.elements {
			let connectivity = element.nodes.iter().map(|id| id.to_string()).collect::<Vec<_>>().join(",");
			writeln!(writer, "\t\t\t<elem id=\"{}\">{}</elem>", element.id, connectivity)?;
		}
		writeln!(writer, "\t\t</Elements>")?;
	}
	writeln!(writer, "\t</Mesh>")?;
	writeln!(writer, "\t<MeshDomains>")?;
	for group in &groups {
		writeln!(writer, "\t\t<SolidDomain name=\"{}\" mat=\"{}\"/>", xml_escape(&group.set_name), xml_escape(&group.material_name))?;
	}
	writeln!(writer, "\t</MeshDomains>")?;
	writeln!(writer, "</febio_spec>")?;

	Ok(out_path)
}

fn parse_febio_file(path: &str) -> Result<ParsedFebioMesh> {
	let content = fs::read_to_string(path)?;
	let lines = content.lines().map(|line| line.trim()).collect::<Vec<_>>();
	let mut index = 0usize;
	let mut name = String::new();
	let mut nodes = Vec::new();
	let mut element_blocks = Vec::new();
	let mut material_moduli_by_name = HashMap::new();
	let mut domain_material_by_set = HashMap::new();
	let mut element_set_moduli: HashMap<String, Vec<f64>> = HashMap::new();

	while index < lines.len() {
		let line = lines[index];
		if line.is_empty() || line.starts_with("<?xml") || line.starts_with("</febio_spec") {
			index += 1;
			continue;
		}

		if line.starts_with("<Nodes") {
			if name.is_empty() {
				name = attr_value(line, "name").unwrap_or_else(|| model_name_from_path(path));
			}
			let (block_nodes, next_index) = parse_nodes_block(&lines, index)?;
			nodes.extend(block_nodes);
			index = next_index;
			continue;
		}

		if line.starts_with("<Elements") {
			let element_type = attr_value(line, "type").ok_or_else(|| anyhow!("FEBio <Elements> block missing type attribute"))?;
			let kind = febio_element_kind(&element_type)?;
			let block_name = attr_value(line, "name");
			let (block_elements, next_index) = parse_elements_block(&lines, index, kind.clone())?;
			element_blocks.push(ParsedElementBlock {
				name: block_name,
				kind,
				elements: block_elements,
			});
			index = next_index;
			continue;
		}

		if line.starts_with("<Material") {
			let (materials, next_index) = parse_material_block(&lines, index)?;
			for (material_name, modulus) in materials {
				material_moduli_by_name.insert(material_name, modulus);
			}
			index = next_index;
			continue;
		}

		if line.starts_with("<MeshDomains") {
			let (domains, next_index) = parse_mesh_domains_block(&lines, index)?;
			for (set_name, material_name) in domains {
				domain_material_by_set.insert(set_name, material_name);
			}
			index = next_index;
			continue;
		}

		if line.starts_with("<ElementData") {
			let set_name = attr_value(line, "elem_set").or_else(|| attr_value(line, "name")).ok_or_else(|| anyhow!("FEBio <ElementData> block missing elem_set/name attribute"))?;
			let (values, next_index) = parse_element_data_block(&lines, index)?;
			element_set_moduli.insert(set_name, values);
			index = next_index;
			continue;
		}

		index += 1;
	}

	if name.is_empty() {
		name = model_name_from_path(path);
	}

	Ok(ParsedFebioMesh {
		name,
		nodes,
		element_blocks,
		material_moduli_by_name,
		domain_material_by_set,
		element_data_by_set: element_set_moduli,
	})
}

fn parse_nodes_block(lines: &[&str], start_index: usize) -> Result<(Vec<Node>, usize)> {
	let mut nodes = Vec::new();
	let mut index = start_index + 1;
	while index < lines.len() {
		let line = lines[index];
		if line.starts_with("</Nodes>") {
			return Ok((nodes, index + 1));
		}
		if line.starts_with("<node") {
			let id = parse_attr_u32(line, "id")?;
			let text = extract_text_between_tags(line, "node").ok_or_else(|| anyhow!("invalid FEBio node line: {line}"))?;
			let coords = parse_xyz(&text)?;
			nodes.push(Node { id, x: coords.0, y: coords.1, z: coords.2 });
		}
		index += 1;
	}
	Err(anyhow!("unterminated <Nodes> block"))
}

fn parse_elements_block(lines: &[&str], start_index: usize, kind: ElementKind) -> Result<(Vec<Element>, usize)> {
	let mut elements = Vec::new();
	let mut index = start_index + 1;
	while index < lines.len() {
		let line = lines[index];
		if line.starts_with("</Elements>") {
			return Ok((elements, index + 1));
		}
		if line.starts_with("<elem") {
			let id = parse_attr_u32(line, "id")?;
			let text = extract_text_between_tags(line, "elem").ok_or_else(|| anyhow!("invalid FEBio element line: {line}"))?;
			let nodes = parse_connectivity(&text)?;
			elements.push(Element { id, nodes, kind: kind.clone() });
		}
		index += 1;
	}
	Err(anyhow!("unterminated <Elements> block"))
}

fn parse_material_block(lines: &[&str], start_index: usize) -> Result<(Vec<(String, f64)>, usize)> {
	let mut materials = Vec::new();
	let mut index = start_index + 1;
	let mut current_name: Option<String> = None;
	let mut current_modulus: Option<f64> = None;

	while index < lines.len() {
		let line = lines[index];
		if line.starts_with("</Material>") {
			if let (Some(name), Some(modulus)) = (current_name.take(), current_modulus.take()) {
				materials.push((name, modulus));
			}
			return Ok((materials, index + 1));
		}

		if line.starts_with("<material") {
			if let (Some(name), Some(modulus)) = (current_name.take(), current_modulus.take()) {
				materials.push((name, modulus));
			}
			current_name = attr_value(line, "name");
			current_modulus = None;
		} else if (line.starts_with("<E>") || line.starts_with("<E "))
			&& let Some(text) = extract_text_between_tags(line, "E") 
				&& let Ok(modulus) = text.trim().parse::<f64>() {
					current_modulus = Some(modulus);
				}
		
		

		index += 1;
	}

	Err(anyhow!("unterminated <Material> block"))
}

fn parse_mesh_domains_block(lines: &[&str], start_index: usize) -> Result<(Vec<(String, String)>, usize)> {
	let mut mappings = Vec::new();
	let mut index = start_index + 1;
	while index < lines.len() {
		let line = lines[index];
		if line.starts_with("</MeshDomains>") {
			return Ok((mappings, index + 1));
		}
		if line.starts_with("<SolidDomain")
			&& let (Some(set_name), Some(material_name)) = (attr_value(line, "name"), attr_value(line, "mat")) {
				mappings.push((set_name, material_name));
			}
		
		index += 1;
	}
	Err(anyhow!("unterminated <MeshDomains> block"))
}

fn parse_element_data_block(lines: &[&str], start_index: usize) -> Result<(Vec<f64>, usize)> {
	let mut values = Vec::new();
	let mut index = start_index + 1;
	while index < lines.len() {
		let line = lines[index];
		if line.starts_with("</ElementData>") {
			return Ok((values, index + 1));
		}
		if line.starts_with("<elem") {
			let text = extract_text_between_tags(line, "elem").ok_or_else(|| anyhow!("invalid FEBio element data line: {line}"))?;
			if !text.trim().is_empty() {
				values.push(text.trim().parse::<f64>()?);
			}
		}
		index += 1;
	}
	Err(anyhow!("unterminated <ElementData> block"))
}

fn collect_nodes(parts: &[&Part]) -> Vec<Node> {
	let mut nodes_by_id = BTreeMap::new();
	for part in parts {
		for node in &part.nodes {
			nodes_by_id.entry(node.id).or_insert_with(|| node.clone());
		}
	}
	nodes_by_id.into_values().collect()
}

fn collect_grouped_moduli(parts: &[&Part], per_part_moduli: &[Vec<f64>], params: &Params) -> Result<Vec<Vec<f64>>> {
	let mut all_raw_moduli = Vec::new();
	for (part_index, part) in parts.iter().enumerate() {
		let moduli = per_part_moduli.get(part_index).ok_or_else(|| anyhow!("FEBio export missing modulus data for part {}", part_index + 1))?;
		if moduli.len() != part.elements.len() {
			return Err(anyhow!("FEBio export modulus count for part {} does not match element count", part_index + 1));
		}
		all_raw_moduli.extend_from_slice(moduli);
	}

	let grouped_all = group_moduli(&all_raw_moduli, params);
	let mut grouped_per_part = Vec::with_capacity(parts.len());
	let mut offset = 0usize;
	for part in parts {
		let count = part.elements.len();
		grouped_per_part.push(grouped_all[offset..offset + count].to_vec());
		offset += count;
	}
	Ok(grouped_per_part)
}

fn collect_groups(parts: &[&Part], grouped_moduli: &[Vec<f64>], materials: &[f64]) -> Result<Vec<GroupedElements>> {
	let mut groups = Vec::new();
	let mut part_group_counters: HashMap<usize, usize> = HashMap::new();

	for (part_index, part) in parts.iter().enumerate() {
		let moduli = grouped_moduli.get(part_index).ok_or_else(|| anyhow!("FEBio export missing grouped modulus data for part {}", part_index + 1))?;
		if moduli.len() != part.elements.len() {
			return Err(anyhow!("FEBio export modulus count for part {} does not match element count", part_index + 1));
		}

		let mut by_key: HashMap<(String, u64), Vec<Element>> = HashMap::new();
		for (element_index, element) in part.elements.iter().enumerate() {
			let modulus = moduli[element_index];
			let key = (febio_element_type(&element.kind).to_string(), modulus.to_bits());
			by_key.entry(key).or_default().push(element.clone());
		}

		for ((element_type, modulus_bits), elements) in by_key {
			let counter = part_group_counters.entry(part_index).or_insert(0);
			*counter += 1;
			let modulus = f64::from_bits(modulus_bits);
			let material_index = find_material_index(materials, modulus).ok_or_else(|| anyhow!("Failed to map modulus to FEBio material"))?;
			let set_name = format!(
				"{}_Set_{}",
				part.name.as_deref().map(sanitize_name).unwrap_or_else(|| format!("Part_{}", part_index + 1)),
				*counter
			);
			groups.push(GroupedElements {
				set_name,
				element_type,
				material_name: format!("Mat_{}", material_index + 1),
				elements,
			});
		}
	}

	Ok(groups)
}

#[derive(Debug)]
struct GroupedElements {
	set_name: String,
	element_type: String,
	material_name: String,
	elements: Vec<Element>,
}

fn collect_materials(grouped_moduli: &[Vec<f64>]) -> Result<Vec<f64>> {
	let mut materials = Vec::<f64>::new();
	for part_moduli in grouped_moduli {
		for &modulus in part_moduli {
			if !materials.iter().any(|existing| approx_equal(*existing, modulus)) {
				materials.push(modulus);
			}
		}
	}
	materials.sort_by(|a, b| a.partial_cmp(b).unwrap());
	Ok(materials)
}

fn find_material_index(materials: &[f64], modulus: f64) -> Option<usize> {
	materials.iter().position(|existing| approx_equal(*existing, modulus))
}

fn lookup_material_modulus(materials: &HashMap<String, f64>, material_name: &str) -> Option<f64> {
	materials
		.get(material_name)
		.copied()
		.or_else(|| materials.iter().find_map(|(name, modulus)| name.eq_ignore_ascii_case(material_name).then_some(*modulus)))
}

fn febio_element_kind(raw: &str) -> Result<ElementKind> {
	match raw.trim().to_ascii_lowercase().as_str() {
		"tet4" | "tetra4" => Ok(ElementKind::Tet4),
		"tet10" | "tetra10" => Ok(ElementKind::Tet10),
		"hex8" | "hex" => Ok(ElementKind::Hex8),
		"penta6" | "wedge6" | "wedge" => Ok(ElementKind::Wedge6),
		other => Err(anyhow!("unsupported FEBio element type: {other}")),
	}
}

fn febio_element_type(kind: &ElementKind) -> &'static str {
	match kind {
		ElementKind::Tet4 => "tet4",
		ElementKind::Tet10 => "tet10",
		ElementKind::Hex8 => "hex8",
		ElementKind::Wedge6 => "penta6",
	}
}

fn parse_xyz(text: &str) -> Result<(f64, f64, f64)> {
	let values = text
		.split(|ch: char| ch == ',' || ch.is_whitespace())
		.filter(|part| !part.is_empty())
		.map(|part| part.parse::<f64>())
		.collect::<Result<Vec<_>, _>>()?;
	if values.len() != 3 {
		return Err(anyhow!("expected 3 coordinates, found {} in '{text}'", values.len()));
	}
	Ok((values[0], values[1], values[2]))
}

fn parse_connectivity(text: &str) -> Result<Vec<u32>> {
	text
		.split(|ch: char| ch == ',' || ch.is_whitespace())
		.filter(|part| !part.is_empty())
		.map(|part| part.parse::<u32>().map_err(Into::into))
		.collect()
}

fn parse_attr_u32(tag: &str, attr: &str) -> Result<u32> {
	attr_value(tag, attr)
		.ok_or_else(|| anyhow!("missing {attr} attribute in '{tag}'"))?
		.parse::<u32>()
		.map_err(Into::into)
}

fn attr_value(tag: &str, name: &str) -> Option<String> {
	let needle = format!("{name}=\"");
	let start = tag.find(&needle)? + needle.len();
	let rest = &tag[start..];
	let end = rest.find('"')?;
	Some(rest[..end].to_string())
}

fn extract_text_between_tags(line: &str, tag_name: &str) -> Option<String> {
	let open = line.find('>')? + 1;
	let close = line.rfind(&format!("</{tag_name}>") )?;
	Some(line[open..close].to_string())
}

fn output_path(orig_mesh_path: &str) -> String {
	if let Some(stripped) = orig_mesh_path.strip_suffix(".feb") {
		format!("{}MAT.feb", stripped)
	} else {
		format!("{orig_mesh_path}_MAT.feb")
	}
}

fn model_name_from_path(orig_mesh_path: &str) -> String {
	std::path::Path::new(orig_mesh_path)
		.file_stem()
		.and_then(|stem| stem.to_str())
		.unwrap_or("FEBioModel")
		.to_string()
}

fn sanitize_name(name: &str) -> String {
	name.chars()
		.map(|ch| if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' { ch } else { '_' })
		.collect()
}

fn format_modulus(value: f64) -> String {
	if !value.is_finite() {
		return "0".to_string();
	}
	let mut text = format!("{:.10}", value);
	while text.contains('.') && text.ends_with('0') {
		text.pop();
	}
	if text.ends_with('.') {
		text.pop();
	}
	text
}

fn approx_equal(a: f64, b: f64) -> bool {
	(a - b).abs() <= 1e-9_f64.max(1e-9_f64 * a.abs().max(b.abs()))
}

fn xml_escape(value: &str) -> String {
	value
		.replace('&', "&amp;")
		.replace('<', "&lt;")
		.replace('>', "&gt;")
		.replace('"', "&quot;")
		.replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
	use super::*;
	use crate::params::Params;

	#[test]
	fn parses_febio_fixture_mesh() {
		let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("febio_test").join("PM15_nomaterial.feb");
		let mesh = parse_feb(path.to_str().unwrap(), &[]).expect("failed to parse FEBio fixture");
		assert_eq!(mesh.parts.len(), 1);
		assert!(!mesh.parts[0].nodes.is_empty());
		assert!(!mesh.parts[0].elements.is_empty());
	}

	#[test]
	fn writes_febio_file() {
		let params_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("febio_test").join("pm15_parameters.toml");
		let params = Params::parse(params_path.to_str().unwrap()).expect("failed to parse FEBio params");
		let mesh = Mesh {
			parts: vec![Part {
				name: Some("ExamplePart".to_string()),
				nodes: vec![
					Node { id: 1, x: 0.0, y: 0.0, z: 0.0 },
					Node { id: 2, x: 1.0, y: 0.0, z: 0.0 },
					Node { id: 3, x: 0.0, y: 1.0, z: 0.0 },
					Node { id: 4, x: 0.0, y: 0.0, z: 1.0 },
					Node { id: 5, x: 1.0, y: 1.0, z: 1.0 },
				],
				elements: vec![
					Element { id: 1, nodes: vec![1, 2, 3, 4], kind: ElementKind::Tet4 },
					Element { id: 2, nodes: vec![2, 3, 4, 5], kind: ElementKind::Tet4 },
				],
				node_index: [(1u32, 0usize), (2, 1), (3, 2), (4, 3), (5, 4)].into_iter().collect(),
				ignore: false,
			}],
			mesh_format_info: Some(MeshFormatInfo::default()),
		};
		let out_path = std::env::temp_dir().join("luma_febio_writer_test.feb");
		let written = write_feb(&mesh, &[vec![16671.14, 16592.1]], &params, out_path.to_str().unwrap()).expect("failed to write FEBio file");
		let content = std::fs::read_to_string(&written).expect("failed to read FEBio output");
		assert!(content.contains("<febio_spec version=\"4.0\">"));
		assert!(content.contains("<material id=\"1\" name=\"Mat_1\" type=\"isotropic elastic\">"));
		let density_1 = params.density_back_calculation(16671.14);
		let density_2 = params.density_back_calculation(16592.1);
		assert!(content.contains(&format!("<density>{}</density>", format_modulus(density_1))));
		assert!(content.contains("<E>16671.14</E>"));
		assert!(content.contains("<material id=\"2\" name=\"Mat_2\" type=\"isotropic elastic\">"));
		assert!(content.contains(&format!("<density>{}</density>", format_modulus(density_2))));
		assert!(content.contains("<E>16592.1</E>"));
		assert!(content.contains("mat=\"Mat_1\"") || content.contains("mat=\"Mat_2\""));
		let _ = std::fs::remove_file(written);
	}

	#[test]
	fn parses_processed_febio_materials() {
		let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("febio_test").join("PM15_nomaterialMAT.feb");
		let (mesh, per_part_moduli) = parse_feb_with_materials(path.to_str().unwrap(), &[]).expect("failed to parse FEBio processed fixture");
		assert_eq!(mesh.parts.len(), 1);
		assert_eq!(per_part_moduli.len(), 1);
		assert_eq!(per_part_moduli[0].len(), mesh.parts[0].elements.len());
		assert!(per_part_moduli[0].iter().any(|value| *value > 0.0));
	}
}
